### ISSUE TITLE
my test wallet address

### ISSUE THREAD

**Issue by revolver007** [evenfound/guide-to-testnet-v0.1.0#9]
n1cKvMBfhseFUwKB9eVmmwtCApotv34pF6

**Comment by annachalova** [comment]
evenctl wallet balance -l n1cKvMBfhseFUwKB9eVmmwtCApotv34pF6

2500 EVENs are there)

**Comment by mankpoeds** [comment]
this my address testnet : mkX8tFoCUUZNPfVE6wfxVkpzaDcUbLJAiQ

**Comment by vinskasenda** [comment]
my wallet address :
mo7wbrycUo87X5bCacXvmm1jcS7AMLWizb

**Comment by slavik342** [comment]
mh7WbEiQF28QH6rHU61XEbxCsyMrL9Awgp

**Comment by marianobrm** [comment]
msGnMk1zpJAJsmd6QGLStDtF4Rc6FsrFBu
